/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface LobbyDBO {
  'display_name': string | null;
  'id': string;
}
export interface LobbyUserDBO {
  'flags': number | null;
  'lobby_id': number | null;
  'user_id': number | null;
}
export interface MediaObjectDBO {
  'duration_ms': number | null;
  'faucet_data': string;
  'id': number;
  'image_url': string | null;
  'lobby_id': number | null;
  'title': string | null;
}
export interface PublicKeyCredentialDBO {
  'counter': number | null;
  'external_id': string | null;
  'public_key': string | null;
  'user_id': number | null;
}
export interface SchemaMigrationDBO {
  'version': string | null;
}
export interface UserDBO {
  'display_name': string | null;
  'id': number;
  'username': string;
}
